### ISSUE TITLE
websockify error parsing listening port

### ISSUE THREAD

**Issue by Kapujino** [ich777/docker-jdownloader2#1]
Hi,

Thanks for this great container!
Previously I used this container on a x64 box without any issues.

I'm now running this on aarch64. The jd2 and vnc work perfectly. But the noVNC does not seem to work. I guess this error message is related:
```
dl_dl-launcher.1.yce84lexmwyf@rp4node01    | jd         | Usage: 
dl_dl-launcher.1.yce84lexmwyf@rp4node01    | jd         |     websockify [options] [source_addr:]source_port [target_addr:target_port]
dl_dl-launcher.1.yce84lexmwyf@rp4node01    | jd         |     websockify [options] [source_addr:]source_port -- WRAP_COMMAND_LINE
dl_dl-launcher.1.yce84lexmwyf@rp4node01    | jd         | 
dl_dl-launcher.1.yce84lexmwyf@rp4node01    | jd         | websockify: error: Error parsing listen port
```
I wonder why this issue happens only on aarch64. Do you have an idea what I can do about this?

Many thanks

**Comment by ich777** [comment]
Thank you for the report. :)

I will look into this tomorrow, have to setup my RaspberryPi and test it on my own, will get back to you when I know more.

**Comment by ich777** [comment]
@Kapujino I haven't got time yet to set up my RaspberryPi but I think I found an issue in the `Dockerfile`.
I've updated the containers already, can you try to update the container and see if it is working now?

**Comment by Kapujino** [comment]
Many thanks, the issue is solved. Works perfectly now.
